name: Generate Github-Pages from markdown files

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Build
        run: |
          export TZ='Asia/Shanghai'
          npm install
          npm run build
          echo "icyfenix.cn" >> .vuepress/dist/CNAME

      - name: Deploy Github-Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .vuepress/dist

      - name: Refresh Tencent CDN
        run: npm run deoply:refresh-cdn
        env:
          CDN_ID: ${{ secrets.CDN_ID }}
          CDN_KEY: ${{ secrets.CDN_KEY }}
        continue-on-error: true
